name: Build and Deploy Next.js App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_BUILD_PATH: ${{ secrets.TEMP_FILE_PATH }}
          DEPLOY_SCRIPT_PATH: ${{ secrets.DEPLOY_SH_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Clean the build directory on the VPS
          ssh -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_HOST "rm -rf $TEMP_FILE_PATH/.next"

          # Upload the new build
          scp -o StrictHostKeyChecking=no -r .next $VPS_USERNAME@$VPS_HOST:$TEMP_FILE_PATH

          # Execute the deploy script
          ssh -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_HOST "sh $DEPLOY_SH_PATH"
